apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Arena
metadata:
  name: guardrails-test
spec:
  # Prompt configurations
  prompt_configs:
    - id: content-filter
      file: prompts/content-filter.yaml

  # Provider configurations
  providers:
    - file: providers/openai.yaml

  # Test scenarios
  scenarios:
    - file: scenarios/guardrail-should-trigger.yaml
    - file: scenarios/guardrail-should-not-trigger.yaml
    - file: scenarios/multiple-violations.yaml
    - file: scenarios/streaming-length-trigger.yaml

  # Default configuration
  defaults:
    provider: openai-gpt4
    prompt_config: content-filter
    temperature: 0.7
    max_tokens: 150
    seed: 42
    timeout: 30s
    output:
      dir: out
      formats: ["json", "html"]
      html:
        file: report.html

