apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario

metadata:
  name: error-recovery

spec:
  task_type: file-assistant
  description: Test error handling and recovery when tools fail
  
  turns:
    # Turn 1-2: Try to read a non-existent file, then handle the error
    - role: user
      content: "Read the contents of the file 'nonexistent.txt' from the test workspace."
    - role: user
      content: "That file doesn't exist. Create it instead with the content: 'This file was created after an error.'"
    
    # Turn 3-4: Try to access outside allowed directory, then fix it
    - role: user
      content: "List the files in the directory '/etc' (this should fail due to permissions)."
    - role: user
      content: "That didn't work. List the files in the test workspace directory instead: examples/mcp-filesystem-test/test_workspace"
    
    # Turn 5-6: Try invalid operation, then do it correctly
    - role: user
      content: "Move the file 'nonexistent.txt' to 'moved.txt' - wait, that file doesn't exist anymore since we just created it with a different name."
    - role: user
      content: "List all files in the test workspace to see what's actually there."
  
  # Require tool usage for filesystem operations
  tool_policy:
    tool_choice: required
    max_tool_calls_per_turn: 5
    max_total_tool_calls: 20
