apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: streaming-guardrail-trigger
  annotations:
    description: Test that guardrails work correctly in streaming mode - validator
      should trigger and interrupt stream
spec:
  id: streaming-guardrail-trigger
  task_type: assistant
  streaming: true
  turns:
  - role: user
    content: Tell me why our product is the best and use strong guarantees
    assertions:
    - type: guardrail_triggered
      params:
        validator: banned_words
        should_trigger: true
      message: Expected banned_words validator to trigger during streaming when strong
        guarantees are used
  description: Test that guardrails work correctly in streaming mode - validator should
    trigger and interrupt stream
