apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: account-info
spec:
  description: "Customer asking about their account details"
  task_type: "customer-support"
  
  turns:
    - role: "user"
      content: "Can you tell me when my subscription renews? My email is mary.wilson@email.com"
      assertions: []
      
      # Expected: Agent should use get_customer_info and check_subscription_status tools
      
    - role: "user"
      content: "Also, what plan am I on currently?"
      assertions:
        - type: content_matches
          params:
            pattern: "(?i)(plan|currently|subscription|Premium|Basic|Pro|Standard)"
            message: "Should provide information about current plan based on previous tool calls"
      
      # Expected: Agent should reference subscription_status from previous tool call
