apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: billing-question
spec:
  description: "Customer asking about a billing discrepancy"
  task_type: "customer-support"
  
  turns:
    - role: "user"
      content: "Hi, I was charged twice for my subscription this month. My email is sarah.jones@email.com. Can you help?"
      assertions:
        - type: tools_called
          params:
            tools: ["get_customer_info", "check_subscription_status"]
            message: "Should use tools to investigate the billing discrepancy"
        - type: content_includes
          params:
            patterns: ["billing", "charged twice", "investigate", "look into"]
            message: "Should acknowledge billing issue and offer to investigate"
      
      # Expected: Agent should use get_customer_info and check_subscription_status tools
      
    - role: "user"  
      content: "Yes, I see two charges of $49.99 on October 15th"
      assertions:
        - type: tools_called
          params:
            tools: ["create_support_ticket"]
            message: "Should create support ticket for billing investigation"
        - type: content_includes
          params:
            patterns: ["understand", "duplicate", "billing team", "investigate"]
            message: "Should acknowledge duplicate charges and escalate to billing team"
      
      # Expected: Agent should use create_support_ticket tool
