apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: order-inquiry
spec:
  description: "Customer asking about order status"
  task_type: "customer-support"
  
  turns:
    - role: "user"
      content: "Hi, I placed an order last week but haven't received it yet. Order number ORD-2024-1234. My email is john.smith@email.com"
      assertions: []
      
      # Expected: Agent should use get_customer_info and get_order_history tools
      
    - role: "user"
      content: "It's been 8 days. The estimated delivery was 5-7 business days."
      assertions: []
      
      # Expected: Agent might use create_support_ticket tool
