apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: orders-flow
spec:
  id: orders-flow
  description: "Orders path: intake → orders (skill activation) → resolve → closed"
  pack: ../workflow-skills.pack.json
  context_carry_forward: true
  steps:
    # Step 1: Customer contacts support about a missing order (intake state)
    - type: input
      content: "I placed an order last week and it still hasn't arrived. Order number is ORD-5432."
      assertions:
        - type: state_is
          params:
            state: intake
        - type: content_matches
          params:
            pattern: "(?i)(order|track|delivery|help)"

    # Step 2: Intake agent routes to orders specialist
    - type: input
      content: "My email is bob@example.com. The estimated delivery was 3 days ago."
      assertions:
        - type: transitioned_to
          params:
            state: orders

    # Step 3: Orders specialist activates troubleshooting skill
    - type: input
      content: "Can you check the tracking status for my order?"
      assertions:
        - type: state_is
          params:
            state: orders
        - type: content_matches
          params:
            pattern: "(?i)(troubleshoot|order|investigat|track)"

    # Step 4: Specialist uses activated skill's tools to look up order
    - type: input
      content: "What's the latest tracking update?"
      assertions:
        - type: state_is
          params:
            state: orders
        - type: content_matches
          params:
            pattern: "(?i)(track|ship|deliver|status|weather)"

    # Step 5: Specialist resolves and transitions to closed
    - type: input
      content: "That's great news, thank you for looking into it."
      assertions:
        - type: transitioned_to
          params:
            state: closed

    # Step 6: Closing summary
    - type: input
      content: "Thanks!"
      assertions:
        - type: workflow_complete
          params: {}

  # Conversation-level assertions
  conversation_assertions:
    - type: skill_activated
      params:
        skill_names: ["order-troubleshooting"]
    - type: skill_not_activated
      params:
        skill_names: ["pci-compliance", "refund-processing"]
