apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: openai-o1
spec:
  id: openai-o1
  type: openai
  model: o1
  defaults:
    temperature: 0.1
    max_tokens: 500
    top_p: 1.0
  pricing:
    input_cost_per_1k: 0.015
    output_cost_per_1k: 0.06
