apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: openai-gpt4o-mini-audio
spec:
  id: openai-gpt4o-mini-audio
  type: openai
  model: gpt-4o-mini-audio-preview
  defaults:
    temperature: 0.1
    max_tokens: 500
    top_p: 1.0
  pricing:
    # Audio tokens: ~$0.01 per minute input, ~$0.04 per minute output
    input_cost_per_1k: 0.01
    output_cost_per_1k: 0.04
  additional_config:
    # Audio models require Chat Completions API (not Responses API)
    api_mode: completions
