apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: openai-gpt4o-mini
spec:
  id: openai-gpt4o-mini
  type: openai
  model: gpt-4o-mini
  defaults:
    temperature: 0.1
    max_tokens: 500
    top_p: 1.0
  pricing:
    input_cost_per_1k: 0.00015
    output_cost_per_1k: 0.0006
