linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/AltairaLabs/PromptKit
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  # Replace gomnd with mnd
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign

linters:
  enable:
    - bodyclose
    - copyloopvar  # replaces exportloopref
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet        # includes shadow detection
    - ineffassign
    - lll
    - misspell
    - mnd          # replaces gomnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused       # replaces deadcode, structcheck, varcheck
    - whitespace

issues:
  exclude-rules:
    # Exclude most linters from test files
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo
        - goconst
        - gosec
        - lll
        - gocritic
        - gochecknoinits
        - unused
        - depguard
        - errcheck
        - staticcheck
        - govet
        - whitespace
        - goimports
    - path: test_.*\.go
      linters:
        - mnd
        - funlen
        - gocyclo
        - goconst
        - gosec
        - lll
        - gocritic
        - gochecknoinits
        - unused
        - depguard
        - errcheck
        - staticcheck
        - govet
        - whitespace
        - goimports
    - path: cmd/
      linters:
        - funlen
    - path: examples/
      linters:
        - mnd
        - funlen
        - gocyclo
        - goconst
        - gosec
        - lll
        - gocritic
        - gochecknoinits
        - unused
        - depguard
        - errcheck
        - staticcheck
        - govet
        - whitespace
        - goimports
  exclude-dirs:
    - vendor
    - bin
    - out

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true