version: "2"

# Linter settings (not for formatters)
linters:
  enable:
    - bodyclose
    - copyloopvar  # replaces exportloopref
    # - depguard   # Disabled - too many false positives with internal imports
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    # - funlen     # Disabled - many legitimately complex functions
    - gochecknoinits
    - goconst
    - gocritic
    - gocognit
    - goprintffuncname
    - gosec
    - govet        # includes shadow detection
    - ineffassign
    - lll
    - misspell
    - mnd          # replaces gomnd
    - nakedret
    - noctx
    - nolintlint
    - revive       # Go style checker - catches non-idiomatic names like Get* functions
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused       # replaces deadcode, structcheck, varcheck
    - whitespace
  settings:
    govet:
      enable:
        - shadow
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 2
      ignore-string-values: 'POST|GET|PUT|DELETE|PATCH'
    misspell:
      locale: US
    lll:
      line-length: 120
    errcheck:
      # Exclude functions where ignoring errors is common practice
      exclude-functions:
        - '(*net/http.Client).CloseIdleConnections'
        - '(*io.Closer).Close'
        - '(io.Closer).Close'
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    revive:
      # Revive is a comprehensive Go style checker that catches various issues including:
      # - Stuttering type names (e.g., mock.MockProvider, prompt.PromptConfig)
      # - Variable/constant/type naming conventions
      # - Package naming issues
      # - Exported symbols without documentation
      #
      # Note: Revive does NOT catch "Get" prefix in function names (flagged by SonarQube)
      # The get-return rule only verifies Get* functions return values, not naming style
      # See: https://go.dev/doc/effective_go#Getters
      rules:
        # Naming conventions for variables, constants, and types
        - name: var-naming
          severity: warning
          disabled: false
          arguments:
            - - "ID" # Accept ID as proper name
              - "API"
              - "HTTP"
              - "JSON"
              - "URL"
              - "XML"
              - "YAML"
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - "checkPrivateReceivers"  # Check receiver names even for private methods
            - "sayRepetitiveInsteadOfStutters"  # Use better wording in error messages
        # Add other useful revive rules
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    paths:
      - vendor
      - bin
      - out
    rules:
      # Exclude errcheck for defer Close() - it's idiomatic to ignore these errors
      - text: "Error return value of.*Close.*is not checked"
        linters:
          - errcheck
      # Exclude most linters from test files
      - path: '_test\.go'
        linters:
          - mnd
          - gocognit
          - goconst
          - gosec
          - lll
          - gocritic
          - gochecknoinits
          - unused
          - depguard
          - errcheck
          - staticcheck
          - govet
          - whitespace
          - revive
      - path: 'test_.*\.go'
        linters:
          - mnd
          - funlen
          - gocognit
          - goconst
          - gosec
          - lll
          - gocritic
          - gochecknoinits
          - unused
          - depguard
          - errcheck
          - staticcheck
          - govet
          - whitespace
          - revive
      - path: 'cmd/'
        linters:
          - funlen
          - gochecknoinits  # cobra CLI tools require init() for command registration
          - revive  # package-comments check not applicable to cmd/main packages
      - path: 'examples/'
        linters:
          - mnd
          - funlen
          - gocognit
          - goconst
          - gosec
          - lll
          - gocritic
          - gochecknoinits
          - unused
          - depguard
          - errcheck
          - staticcheck
          - govet
          - whitespace

# Formatter settings (goimports is a formatter in v2)
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/AltairaLabs/PromptKit
  exclusions:
    paths:
      - vendor
      - bin
      - out

run:
  timeout: 5m
  tests: false

output:
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true