version: "2"

# Linter settings (not for formatters)
linters:
  enable:
    - bodyclose
    - copyloopvar  # replaces exportloopref
    # - depguard   # Disabled - too many false positives with internal imports
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    # - funlen     # Disabled - many legitimately complex functions
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet        # includes shadow detection
    - ineffassign
    - lll
    - misspell
    - mnd          # replaces gomnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused       # replaces deadcode, structcheck, varcheck
    - whitespace
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    lll:
      line-length: 120
    errcheck:
      # Exclude functions where ignoring errors is common practice
      exclude-functions:
        - '(*net/http.Client).CloseIdleConnections'
        - '(*io.Closer).Close'
        - '(io.Closer).Close'
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
  exclusions:
    paths:
      - vendor
      - bin
      - out
    rules:
      # Exclude errcheck for defer Close() - it's idiomatic to ignore these errors
      - text: "Error return value of.*Close.*is not checked"
        linters:
          - errcheck
      # Exclude most linters from test files
      - path: '_test\.go'
        linters:
          - mnd
          - gocyclo
          - goconst
          - gosec
          - lll
          - gocritic
          - gochecknoinits
          - unused
          - depguard
          - errcheck
          - staticcheck
          - govet
          - whitespace
      - path: 'test_.*\.go'
        linters:
          - mnd
          - funlen
          - gocyclo
          - goconst
          - gosec
          - lll
          - gocritic
          - gochecknoinits
          - unused
          - depguard
          - errcheck
          - staticcheck
          - govet
          - whitespace
      - path: 'cmd/'
        linters:
          - funlen
      - path: 'examples/'
        linters:
          - mnd
          - funlen
          - gocyclo
          - goconst
          - gosec
          - lll
          - gocritic
          - gochecknoinits
          - unused
          - depguard
          - errcheck
          - staticcheck
          - govet
          - whitespace

# Formatter settings (goimports is a formatter in v2)
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/AltairaLabs/PromptKit
  exclusions:
    paths:
      - vendor
      - bin
      - out

run:
  timeout: 5m
  tests: false

output:
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true