# GoReleaser configuration for PromptKit
# See: https://goreleaser.com

version: 2

# Build configuration
builds:
  - id: promptarena
    binary: promptarena
    main: ./tools/arena/cmd/promptarena
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/AltairaLabs/PromptKit/tools/arena/cmd/promptarena/version.Version={{.Version}}
      - -X github.com/AltairaLabs/PromptKit/tools/arena/cmd/promptarena/version.Commit={{.Commit}}
      - -X github.com/AltairaLabs/PromptKit/tools/arena/cmd/promptarena/version.Date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

  - id: packc
    binary: packc
    main: ./tools/packc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/AltairaLabs/PromptKit/tools/packc/version.Version={{.Version}}
      - -X github.com/AltairaLabs/PromptKit/tools/packc/version.Commit={{.Commit}}
      - -X github.com/AltairaLabs/PromptKit/tools/packc/version.Date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

# Archive configuration
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

# Checksum configuration
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot configuration (for non-tagged builds)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - 'typo'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other Changes'
      order: 999

# GitHub Release configuration
release:
  github:
    owner: AltairaLabs
    name: PromptKit
  
  # Draft release (review before publishing)
  draft: true
  
  # Release name template
  name_template: "PromptKit {{.Version}}"
  
  # Release notes
  header: |
    ## PromptKit {{.Version}}
    
    ### Installation
    
    **CLI Tools:**
    ```bash
    # Arena
    go install github.com/AltairaLabs/PromptKit/tools/arena/cmd/promptarena@{{.Version}}
    
    # PackC
    go install github.com/AltairaLabs/PromptKit/tools/packc@{{.Version}}
    ```
    
    **SDK Library:**
    ```bash
    go get github.com/AltairaLabs/PromptKit/sdk@{{.Version}}
    ```
    
    **Or download pre-built binaries below** ⬇️
  
  footer: |
    ---
    
    ### Components Released
    
    **Libraries:**
    - `runtime/{{.Version}}` - Core runtime components
    - `pkg/{{.Version}}` - Shared packages
    - `sdk/{{.Version}}` - Production SDK library
    
    **Tools:**
    - `tools/arena/{{.Version}}` - Arena CLI (binaries above)
    - `tools/packc/{{.Version}}` - PackC CLI (binaries above)
    
    ### Installation Methods
    
    1. **Pre-built Binaries** (fastest): Download from assets above
    2. **Go Install** (latest Go): Use commands shown above
    3. **Build from Source**: Clone repo and run `make build`
    
    ### Verification
    
    All binaries are checksummed. Verify downloads:
    ```bash
    shasum -a 256 -c checksums.txt
    ```
    
    ---
    
    **Full Changelog**: https://github.com/AltairaLabs/PromptKit/compare/{{.PreviousTag}}...{{.Tag}}

# Homebrew casks (replaces deprecated brews)
homebrew_casks:
  - name: promptkit
    repository:
      owner: AltairaLabs
      name: homebrew-tap
      branch: main
    homepage: https://github.com/AltairaLabs/PromptKit
    description: "Prompt testing and evaluation toolkit for AI applications"
    license: "Apache-2.0"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    binaries:
      - promptarena
      - packc

# Docker images (disabled for now - will migrate to dockers_v2 after testing basic releases)
# dockers:
#   - image_templates:
#       - "ghcr.io/altairalabs/promptarena:{{ .Version }}"
#       - "ghcr.io/altairalabs/promptarena:{{ .Major }}.{{ .Minor }}"
#       - "ghcr.io/altairalabs/promptarena:{{ .Major }}"
#       - "ghcr.io/altairalabs/promptarena:latest"
#     dockerfile: Dockerfile.arena
#     use: buildx
#     build_flag_templates:
#       - "--pull"
#       - "--platform=linux/amd64,linux/arm64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title=promptarena"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"
#     goos: linux
#     goarch: amd64
#     ids:
#       - promptarena
#   
#   - image_templates:
#       - "ghcr.io/altairalabs/packc:{{ .Version }}"
#       - "ghcr.io/altairalabs/packc:{{ .Major }}.{{ .Minor }}"
#       - "ghcr.io/altairalabs/packc:{{ .Major }}"
#       - "ghcr.io/altairalabs/packc:latest"
#     dockerfile: Dockerfile.packc
#     use: buildx
#     build_flag_templates:
#       - "--pull"
#       - "--platform=linux/amd64,linux/arm64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title=packc"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"
#     goos: linux
#     goarch: amd64
#     ids:
#       - packc

# Announce (optional - uncomment to announce releases)
# announce:
#   slack:
#     enabled: true
#     message_template: 'PromptKit {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}'
