apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Tool
metadata:
  name: calculate
spec:
  description: Perform mathematical calculations
  input_schema:
    type: object
    properties:
      expression:
        type: string
        description: Mathematical expression to evaluate
    required:
    - expression
  output_schema:
    type: string
  mode: mock
  mock_result: '42'
  name: calculate
  timeout_ms: 5000
