apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Arena

metadata:
  name: mcp-filesystem-test
  description: Test filesystem operations via MCP server

spec:
  # MCP Server Configuration
  mcp_servers:
    - name: filesystem
      command: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-filesystem"
        - "examples/mcp-filesystem-test"
      env:
        PATH: "/opt/homebrew/opt/libpq/bin:/Users/chaholl/.nvm/versions/node/v22.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

  # Prompt Configuration
  prompt_configs:
    - id: file-assistant
      file: prompts/file-assistant.yaml

  # Test Scenarios
  scenarios:
    - file: scenarios/file-operations.yaml
    - file: scenarios/error-recovery.yaml

  # Provider Configuration
  providers:
    - file: providers/openai-gpt4o-mini.yaml

  # Default Settings
  defaults:
    temperature: 0.7
    max_tokens: 1000
    seed: 42
    concurrency: 1
    
    # Output configuration for CI/CD test results integration
    output:
      dir: out
      formats: ["json", "junit", "html"]  # Detailed results, CI/CD integration, human-readable reports
      html:
        file: report.html
