#!/usr/bin/env bash
# generate-matrix.sh - Generate capability matrix from promptarena JSON results
#
# Usage: ./scripts/generate-matrix.sh [output_dir]

set -e

OUTPUT_DIR="${1:-out}"
MATRIX_FILE="${OUTPUT_DIR}/CAPABILITY_MATRIX.md"

echo "Generating capability matrix from $OUTPUT_DIR..."

# Check for jq
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed"
    exit 1
fi

# Check if result files exist
if ! ls "$OUTPUT_DIR"/*.json 1> /dev/null 2>&1; then
    echo "No JSON result files found in $OUTPUT_DIR"
    exit 1
fi

# Build aggregated results using jq
# Extract provider, scenario, and pass/fail status from each result file
# Note: JSON uses ProviderID, ScenarioID (uppercase), and successful runs have no Error field
# Process files in reverse order by timestamp (newest first) so we only keep the most recent result
RESULTS=$(for f in $(ls -r "$OUTPUT_DIR"/*.json 2>/dev/null); do
    [[ "$(basename "$f")" == "index.json" ]] && continue
    jq -c '{
        provider: .ProviderID,
        scenario: .ScenarioID,
        passed: (.Messages[-1].meta.assertions.passed // false),
        has_error: (has("Error") and .Error != null and .Error != "")
    }' "$f" 2>/dev/null || true
done | jq -s 'group_by([.provider, .scenario]) | map(.[0])')

# Generate markdown
cat > "$MATRIX_FILE" << 'HEADER'
# Provider Capability Matrix

*Auto-generated by `make capability-matrix`*

## Legend

| Symbol | Meaning |
|--------|---------|
| Pass | Tested and working |
| Fail | Tested and failed |
| Err | Test error |
| - | Not tested |

HEADER

# Define provider groups and display names as JSON for jq processing
PROVIDER_CONFIG='{
  "OpenAI": {
    "providers": [
      {"id": "openai-gpt52", "name": "GPT-5.2"},
      {"id": "openai-gpt52-pro", "name": "GPT-5.2 Pro"},
      {"id": "openai-gpt51", "name": "GPT-5.1"},
      {"id": "openai-gpt5", "name": "GPT-5"},
      {"id": "openai-gpt5-mini", "name": "GPT-5 Mini"},
      {"id": "openai-gpt5-nano", "name": "GPT-5 Nano"},
      {"id": "openai-gpt5-pro", "name": "GPT-5 Pro"},
      {"id": "openai-gpt41", "name": "GPT-4.1"},
      {"id": "openai-gpt41-mini", "name": "GPT-4.1 Mini"},
      {"id": "openai-gpt41-nano", "name": "GPT-4.1 Nano"},
      {"id": "openai-gpt4o", "name": "GPT-4o"},
      {"id": "openai-gpt4o-mini", "name": "GPT-4o Mini"},
      {"id": "openai-o1", "name": "o1"},
      {"id": "openai-o1-pro", "name": "o1-pro"},
      {"id": "openai-o3", "name": "o3"},
      {"id": "openai-o3-mini", "name": "o3-mini"},
      {"id": "openai-o4-mini", "name": "o4-mini"}
    ]
  },
  "Anthropic": {
    "providers": [
      {"id": "anthropic-opus45", "name": "Claude Opus 4.5"},
      {"id": "anthropic-sonnet45", "name": "Claude Sonnet 4.5"},
      {"id": "anthropic-haiku45", "name": "Claude Haiku 4.5"},
      {"id": "anthropic-opus41", "name": "Claude Opus 4.1"},
      {"id": "anthropic-opus4", "name": "Claude Opus 4"},
      {"id": "anthropic-sonnet4", "name": "Claude Sonnet 4"},
      {"id": "anthropic-sonnet37", "name": "Claude 3.7 Sonnet"}
    ]
  },
  "Google": {
    "providers": [
      {"id": "gemini-3-pro", "name": "Gemini 3 Pro"},
      {"id": "gemini-3-flash", "name": "Gemini 3 Flash"},
      {"id": "gemini-25-pro", "name": "Gemini 2.5 Pro"},
      {"id": "gemini-25-flash", "name": "Gemini 2.5 Flash"},
      {"id": "gemini-25-flash-lite", "name": "Gemini 2.5 Flash Lite"},
      {"id": "gemini-20-flash", "name": "Gemini 2.0 Flash"},
      {"id": "gemini-20-flash-lite", "name": "Gemini 2.0 Flash Lite"}
    ]
  }
}'

SCENARIOS='["text-basic", "streaming", "vision", "tools", "json-mode", "audio", "video"]'
HEADERS='["Text", "Stream", "Vision", "Tools", "JSON", "Audio", "Video"]'

# Function to generate table for a provider group
generate_table() {
    local group_name="$1"

    echo "## $group_name" >> "$MATRIX_FILE"
    echo "" >> "$MATRIX_FILE"

    # Header row
    printf "| Model |" >> "$MATRIX_FILE"
    echo "$HEADERS" | jq -r '.[] | " \(.) |"' | tr -d '\n' >> "$MATRIX_FILE"
    echo "" >> "$MATRIX_FILE"

    # Separator row
    printf "|-------|" >> "$MATRIX_FILE"
    echo "$HEADERS" | jq -r '.[] | "------|"' | tr -d '\n' >> "$MATRIX_FILE"
    echo "" >> "$MATRIX_FILE"

    # Data rows
    echo "$PROVIDER_CONFIG" | jq -r --arg group "$group_name" '.[$group].providers[] | "\(.id)|\(.name)"' | while IFS='|' read -r provider_id provider_name; do
        printf "| %s |" "$provider_name" >> "$MATRIX_FILE"

        echo "$SCENARIOS" | jq -r '.[]' | while read -r scenario; do
            # Find result for this provider/scenario
            result=$(echo "$RESULTS" | jq -r --arg p "$provider_id" --arg s "$scenario" '
                .[] | select(.provider == $p and .scenario == $s) |
                if .has_error == true then "Err"
                elif .passed == true then "Pass"
                elif .passed == false then "Fail"
                else "-"
                end
            ' | head -1)

            # Default to "-" if no result found
            [[ -z "$result" ]] && result="-"

            printf " %s |" "$result" >> "$MATRIX_FILE"
        done
        echo "" >> "$MATRIX_FILE"
    done

    echo "" >> "$MATRIX_FILE"
}

# Generate tables for each provider group
generate_table "OpenAI"
generate_table "Anthropic"
generate_table "Google"

# Footer
echo "---" >> "$MATRIX_FILE"
echo "" >> "$MATRIX_FILE"
echo "*Generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')*" >> "$MATRIX_FILE"

echo "Capability matrix generated: $MATRIX_FILE"
