apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: mock-docs
spec:
  id: "mock-docs"
  type: mock
  model: mock-document-analyzer-v1
  additional_config:
    mock_config: mock-responses.yaml
  include_raw_output: true
  defaults:
    temperature: 0.7
    max_tokens: 2000
    top_p: 1.0
