apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Arena
metadata:
  name: arena-media-test
spec:
  providers:
    - file: providers/mock-provider.yaml

  scenarios:
    - file: image-analysis.yaml
    - file: image-url.yaml
    - file: multimodal-mixed.yaml
    - file: audio-transcription.yaml
    - file: mixed-media.yaml
    - file: all-formats.yaml
    - file: image-validation.yaml
    - file: audio-validation.yaml
    - file: video-validation.yaml

  defaults:
    temperature: 0.7
    max_tokens: 1000
    concurrency: 2
    output:
      dir: out
      formats: ["json", "html"]
      html:
        file: report.html
