apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: mixed-media
spec:
  provider: mock-media
  task_type: media-test
  description: "Test mixing different media types (images and audio)"

  turns:
    - role: user
      parts:
        - type: text
          text: "Here's an image and an audio file together:"
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.jpg
            mime_type: image/jpeg
        - type: audio
          media:
            file_path: ../../tools/arena/testdata/media/test-audio-small.wav
            mime_type: audio/wav
      assertions:
        - type: content_includes
          params:
            patterns:
              - "image"
              - "audio"

    - role: user
      parts:
        - type: text
          text: "Analyze these multiple images:"
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.jpg
            mime_type: image/jpeg
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.png
            mime_type: image/png
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.gif
            mime_type: image/gif
      assertions:
        - type: content_includes
          params:
            patterns:
              - "JPEG"
              - "PNG"
