apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Eval
metadata:
  name: basic-eval
spec:
  id: basic-eval-test
  description: Test evaluation of a saved conversation
  recording:
    path: ../recordings/customer-support.arena.json
    type: arena_output
  
  turns:
    - all_turns:
        assertions:
          - type: contains
            params:
              patterns:
                - "you"
  
  conversation_assertions:
    - type: contains_any
      message: "Conversation includes customer support language"
      params:
        patterns:
          - "refund"
          - "help you"
          - "apologize"
        case_sensitive: false
    
    - type: llm_judge_session
      message: "Agent maintains professional tone throughout"
      params:
        criteria: "Does the customer support agent maintain a professional, helpful, and courteous tone throughout the conversation?"
        judge: gpt-4o-judge
        min_score: 0.8
  
  tags:
    - test
    - geography
  mode: instant
