apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Eval
metadata:
  name: basic-eval
spec:
  id: basic-eval-test
  description: Test evaluation of a saved conversation
  recording:
    path: ../recordings/customer-support.arena.json
    type: arena_output
  
  turns:
    - all_turns:
        assertions:
          - type: contains
            params:
              patterns:
                - "you"
  
  conversation_assertions:
    - type: contains_any
      message: "Conversation includes customer support language"
      params:
        patterns:
          - "refund"
          - "help you"
          - "apologize"
        case_sensitive: false
    
    - type: content_excludes
      message: "Agent should not use inappropriate language"
      params:
        patterns:
          - "I don't know"
          - "not my problem"
          - "figure it out yourself"
        case_sensitive: false
  
  tags:
    - test
    - geography
  mode: instant
