apiVersion: promptkit.altaira.ai/v1alpha1
kind: Arena
metadata:
  name: statestore-example
spec:
  # Configure StateStore for conversation persistence
  state_store:
    type: memory  # or "redis" for production
    # redis:
    #   address: "localhost:6379"
    #   password: ""
    #   database: 0
    #   ttl: "24h"
    #   prefix: "promptkit"

  providers:
    - file: provider.yaml

  scenarios:
    - file: scenario.yaml

  defaults:
    temperature: 0.7
    max_tokens: 1000
    seed: 42
    concurrency: 3
    output:
      dir: out
      formats: ["json", "html"]
      html:
        file: report.html
