apiVersion: promptkit.altaira.ai/v1alpha1
kind: Scenario
metadata:
  name: multi-turn-conversation
spec:
  id: multi-turn-conversation
  task_type: customer-support
  turns:
    - role: user
      content: "Hello, I need help with my order"
      assertions:
        - type: content_includes
          params:
            patterns: ["hello", "help", "order", "assist"]
            message: "Should acknowledge greeting and offer to help with order"
    - role: user
      content: "My order number is 12345"
      assertions:
        - type: content_includes
          params:
            patterns: ["12345", "order", "look up", "check"]
            message: "Should acknowledge order number and indicate looking it up"
    - role: user
      content: "When will it arrive?"
      assertions:
        - type: content_includes
          params:
            patterns: ["arrive", "delivery", "shipping", "expect"]
            message: "Should provide delivery information or estimate based on order lookup"
