apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: gemini-flash
spec:
  id: "gemini-flash"
  type: gemini
  model: gemini-3-flash-preview
  include_raw_output: true  # Include raw API requests/responses in output for debugging
  defaults:
    temperature: 0.7
    max_tokens: 1500
    top_p: 1.0
