apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: openai-gpt-4o-mini-real

spec:
  id: openai-gpt-4o-mini
  type: openai
  model: gpt-4o-mini
  base_url: https://api.openai.com/v1
  
  defaults:
    temperature: 0.7
    top_p: 1.0
    max_tokens: 500
  
  rate_limit:
    rps: 10
    burst: 20
  
  pricing:
    input_cost_per_1k: 0.00015
    output_cost_per_1k: 0.0006

  pricing_correct_at: "2024-07-18"
