apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Arena

metadata:
  name: mcp-chatbot-example
  description: Conversational AI with persistent memory via MCP

spec:
  # MCP Server Configuration
  mcp_servers:
    - name: memory
      command: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-memory"
      env:
        PATH: "make sure node is on your path"

  # Prompt Configuration
  prompt_configs:
    - id: memory-assistant
      file: prompts/memory-assistant.yaml

  # Test Scenarios
  scenarios:
    - file: scenarios/memory-conversations.yaml

  # Provider Configuration
  providers:
    - file: providers/openai-gpt4o-mini.yaml

  # Default Settings
  defaults:
    temperature: 0.7
    max_tokens: 1000
    seed: 42
    concurrency: 3
    output:
      dir: out
      formats: ["json", "html"]
      html:
        file: report.html

