apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: claude-3-5-haiku
spec:
  id: claude-3-5-haiku
  type: claude
  model: claude-3-5-haiku-20241022
  base_url: https://api.anthropic.com/v1
  pricing:
    input_cost_per_1k: 0.001
    output_cost_per_1k: 0.005
  defaults:
    temperature: 0.7
    max_tokens: 1500
    top_p: 1.0
