apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: context-limited-fail
  annotations:
    test_goal: verify execution fails when budget exceeded with fail strategy
spec:
  id: context-limited-fail
  task_type: chat
  description: Test 'fail' strategy - errors when budget exceeded
  context_policy:
    token_budget: 300
    reserve_for_output: 150
    strategy: fail
  turns:
  - role: user
    content: Tell me about the solar system.
    assertions:
    - type: content_includes
      params:
        patterns:
        - solar system
  - role: user
    content: What are all the planets in detail?
    assertions:
    - type: content_includes
      params:
        patterns:
        - Mercury
        - Venus
        - Earth
        - Mars
  - role: user
    content: Tell me everything about Jupiter, Saturn, and their moons.
    assertions:
    - type: content_includes
      params:
        patterns:
        - Jupiter
        - Saturn
        - moons
  - role: user
    content: Now explain the asteroid belt and Kuiper belt in great detail.
  context_metadata:
    domain: astronomy
