apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: context-unlimited
spec:
  task_type: chat
  description: "Baseline: No context limits (default behavior)"
  
  # No context_policy = unlimited context (backward compatible)
  
  turns:
    - role: user
      content: "Tell me about the solar system."
    
    - role: user
      content: "What are the inner planets?"
    
    - role: user
      content: "What about the outer planets?"
    
    - role: user
      content: "Which planet is largest?"
    
    - role: user
      content: "What did I first ask you about?"  # Tests full context retention

  context_metadata:
    domain: "astronomy"
    role: "science tutor"
    user_context: "student asking about space"
    session_goal: "educate about the solar system"
