apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Tool

metadata:
  name: get_weather

spec:
  name: get_weather
  description: Get the current weather for a location
  input_schema:
    type: object
    properties:
      location:
        type: string
        description: The city or location to get weather for
    required:
      - location
  output_schema:
    type: string
  mode: mock
  mock_result: "Sunny, 72F"
  timeout_ms: 5000
