apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario

metadata:
  name: streaming-tools-vision

spec:
  id: streaming-tools-vision
  task_type: capability-test
  description: "Test streaming with tools and image input"
  required_capabilities:
    - streaming
    - tools
    - vision
  streaming: true

  turns:
    - role: user
      parts:
        - type: text
          text: "Look at this image and call the analyze_image tool with a description of what you see. Then say CAPABILITY_PASS."
        - type: image
          media:
            url: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
            mime_type: "image/png"
      assertions:
        - type: tools_called
          message: "Should call the analyze_image tool"
          params:
            tools:
              - "analyze_image"
        - type: content_includes
          message: "Response should include CAPABILITY_PASS"
          params:
            patterns: ["CAPABILITY_PASS"]
