apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario

metadata:
  name: streaming-tools

spec:
  id: streaming-tools
  task_type: capability-test
  description: "Test streaming with tool calls"
  required_capabilities:
    - streaming
    - tools
  streaming: true

  turns:
    - role: user
      content: "Call the get_weather function with location='test_city' and then say CAPABILITY_PASS."
      assertions:
        - type: tools_called
          message: "Should call the get_weather tool"
          params:
            tools:
              - "get_weather"
        - type: tool_calls_with_args
          message: "Should call get_weather with location='test_city'"
          params:
            tool_name: "get_weather"
            expected_args:
              location: "test_city"
        - type: content_includes
          message: "Response should include CAPABILITY_PASS after tool call"
          params:
            patterns: ["CAPABILITY_PASS"]
