apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario

metadata:
  name: video

spec:
  id: video
  task_type: capability-test
  description: "Test video input understanding capability"
  required_capabilities:
    - video
  tool_policy:
    tool_choice: none
    max_tool_calls_per_turn: 0
    max_total_tool_calls: 0

  turns:
    - role: user
      parts:
        - type: text
          text: "Watch this video and describe what animal or action you see. End your response with CAPABILITY_PASS."
        - type: video
          media:
            # Using a reliable public test video sample - cat video
            url: "https://storage.googleapis.com/cloud-samples-data/video/cat.mp4"
            mime_type: "video/mp4"
      assertions:
        - type: content_includes
          message: "Response should include CAPABILITY_PASS"
          params:
            patterns: ["CAPABILITY_PASS"]
        - type: content_matches
          message: "Response should describe the cat video content (mentions cat, kitten, animal, etc.)"
          params:
            pattern: "(?i)(cat|kitten|feline|animal|pet|fur|paw|whisker|meow|playing|moving)"
