apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario

metadata:
  name: video

spec:
  id: video
  task_type: capability-test
  description: "Test video input understanding capability"
  provider_group: video

  turns:
    - role: user
      parts:
        - type: text
          text: "Describe what you see in this video. If you cannot process video, say 'VIDEO_NOT_SUPPORTED'. Otherwise end your response with CAPABILITY_PASS."
        - type: video
          media:
            # Using a reliable public test video sample
            url: "https://storage.googleapis.com/cloud-samples-data/video/cat.mp4"
            mime_type: "video/mp4"
      assertions:
        - type: content_matches
          params:
            pattern: "(?i)(CAPABILITY_PASS|VIDEO_NOT_SUPPORTED|cannot|unable|don't|video)"
            message: "Should either process video or indicate inability"
