apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario

metadata:
  name: vision

spec:
  id: vision
  task_type: capability-test
  description: "Test vision/image understanding capability"
  required_capabilities:
    - vision
  tool_policy:
    tool_choice: none
    max_tool_calls_per_turn: 0
    max_total_tool_calls: 0

  turns:
    - role: user
      parts:
        - type: text
          text: "Describe what you see in this image. What company or brand is shown? End your response with CAPABILITY_PASS."
        - type: image
          media:
            # Using a simple, reliably-accessible test image
            url: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
            mime_type: "image/png"
      assertions:
        - type: content_includes
          message: "Response should include CAPABILITY_PASS"
          params:
            patterns: ["CAPABILITY_PASS"]
        - type: content_matches
          message: "Response should describe the Google logo (mentions Google, logo, colors, or letters)"
          params:
            pattern: "(?i)(google|logo|brand|colorful|letters|text|red|blue|green|yellow)"
