#!/usr/bin/env bash
# Fail if the committed SDK-owned reference pages are stale vs Go source.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
"$ROOT/docs/scripts/gen-sdk-reference.sh" "$TMP" >/dev/null
# index.md, runtime-config.md, exec-protocol.md are hand-written pages in the
# same directory that are not generated by gen-sdk-reference.sh (no MAP row).
if ! diff -ru "$ROOT/docs/src/content/docs/sdk/reference" "$TMP" \
     --exclude='index.md' --exclude='runtime-config.md' --exclude='exec-protocol.md' >/dev/null; then
  echo "❌ SDK reference is stale — run 'make docs-sdk-reference' and commit." >&2
  diff -ru "$ROOT/docs/src/content/docs/sdk/reference" "$TMP" \
    --exclude='index.md' --exclude='runtime-config.md' --exclude='exec-protocol.md' >&2 || true
  exit 1
fi
echo "✅ SDK reference is up to date."
