# yaml-language-server: $schema=https://promptkit.altairalabs.ai/schemas/latest/provider.json
#
# OpenAI GPT-4o Realtime Provider
# Realtime API support for bidirectional audio streaming with low latency.
#
apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: openai-gpt4o-realtime

spec:
  id: openai-gpt4o-realtime
  type: openai
  model: gpt-4o-realtime-preview

  # Provider defaults
  defaults:
    temperature: 0.7
    top_p: 1.0
    max_tokens: 1000

  # OpenAI Realtime API configuration
  additional_config:
    # Use realtime API endpoint
    realtime: true
    # Voice configuration
    voice: alloy
    # Audio format settings
    audio_format: pcm16
