package main

import (
	"fmt"
	"sort"
	"strings"
)

// goName converts a schema property name to an exported Go field name.
// initialisms matches the repo's existing spelling (ID, URL, USD, Ms).
var initialisms = map[string]string{
	"id": "ID", "url": "URL", "usd": "USD", "api": "API", "json": "JSON",
	"http": "HTTP", "uri": "URI", "ms": "Ms", "ttl": "TTL", "a2a": "A2A",
	"mcp": "MCP", "ai": "AI", "p95": "P95",
	// Size units follow the repo spelling (MaxSizeMB, not MaxSizeMb).
	"mb": "MB", "kb": "KB", "gb": "GB",
}

// rootTypeName is the Go name for the schema's root object.
const rootTypeName = "Pack"

// JSON-Schema type names used in more than one place.
const (
	typeObject = "object"
	typeString = "string"
	typeBool   = "boolean"
	goBool     = "bool"
	goInt      = "int"
	typeInt    = "integer"
	typeNum    = "number"
	goFloat    = "float64"
	typeArray  = "array"
	goAny      = "any"
	goAnySlice = "[]any"
	goAnyMap   = "map[string]any"
)

func goName(s string) string {
	s = strings.TrimPrefix(s, "$")
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// Emitter turns the schema into Go source.
//
// Design constraints, all chosen to make the output alias-compatible with the
// hand-written types it will replace:
//
//   - VALUE types for optional scalars, not pointers. An off-the-shelf generator
//     makes 42% of fields pointers, which changes every read site
//     (*p.AvgTokens vs p.AvgTokens) across seven packages. Nullability is
//     expressed in this spec exactly once, as type: ["integer","null"], and only
//     that case becomes a pointer.
//   - `date` stays a string, not a time.Time — that is what the hand-written
//     types use and what packs round-trip today.
//   - json + yaml tags only. No mapstructure, no omitzero.
//   - required fields carry no omitempty: a required field that vanishes on
//     serialize produces a pack that fails its own validation.
type Emitter struct {
	schema *Schema
	cov    *Coverage
	ex     *Exclusions
	pkg    string

	// hoisted holds inline objects lifted to named types, keyed by the name
	// they were given, emitted after the $defs so output stays deterministic.
	// The spec nests one (Eval.threshold); rather than flatten it to
	// map[string]any — which would lose every field name and silently accept
	// anything — it becomes EvalThreshold.
	hoisted     map[string]string
	hoistedName []string

	// openNames records every emitted type that accepts extensions.
	openNames []string

	// needsJSON records that a generated variant wrapper uses encoding/json.
	needsJSON bool
}

func NewEmitter(s *Schema, c *Coverage, e *Exclusions, pkg string) *Emitter {
	return &Emitter{schema: s, cov: c, ex: e, pkg: pkg, hoisted: map[string]string{}}
}

func (e *Emitter) Generate() (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by tools/packspec-gen. DO NOT EDIT.\n//\n")
	b.WriteString("// Source: runtime/prompt/schema/promptpack.schema.json (a verbatim mirror of the\n")
	b.WriteString("// published PromptPack release — see runtime/prompt/schema/schema.go).\n//\n")
	b.WriteString("// Regenerate with `make packspec`. CI fails if the committed output differs,\n")
	b.WriteString("// and the generator itself fails if the schema contains anything it does not\n")
	b.WriteString("// account for, so a spec change cannot land here silently.\n")
	fmt.Fprintf(&b, "package %s\n", e.pkg)

	// Body first: emitting it sets needsJSON, which decides the import block.
	body, err := e.generateBody()
	if err != nil {
		return "", err
	}
	if e.needsJSON {
		b.WriteString("\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n")
	}
	b.WriteString(body)
	return b.String(), nil
}

func (e *Emitter) generateBody() (string, error) {
	var b strings.Builder

	for _, name := range e.schema.DefNames {
		e.cov.DeclareDef(name)
		def := e.schema.Defs[name]

		// An excluded def's properties are covered by the exclusion — the
		// hand-written type it defers to owns them. Declaring them here would
		// demand a field on a type this generator does not emit.
		if reason := e.ex.Def(name); reason != "" {
			fmt.Fprintf(&b, "\n// %s is NOT generated: %s\n", name, wrapComment(reason, "// "))
			continue
		}

		var src string
		var err error
		if def.isUnion() {
			src, err = e.emitFlattenedUnion(name, def)
		} else {
			src, err = e.emitDef(name, def)
		}
		if err != nil {
			return "", err
		}
		b.WriteString(src)
		e.cov.EmitDef(name)
	}

	// The root document is an object like any other, and its properties must be
	// accounted for too. Walking only $defs left the root's 17 properties —
	// metadata among them — undeclared, so a spec addition there (RFC 0013's
	// metadata.governance is exactly this shape) would have been silently
	// absent with the coverage check still reporting success.
	//
	// The hand-written prompt.Pack keeps its non-spec extras (FilePath, the
	// workflow aliases, a custom UnmarshalJSON); this is the spec shape beside
	// it, not a replacement for it.
	e.cov.DeclareDef(rootTypeName)
	rootSrc, err := e.emitDef(rootTypeName, e.schema.Root)
	if err != nil {
		return "", err
	}
	b.WriteString(rootSrc)
	e.cov.EmitDef(rootTypeName)

	sort.Strings(e.hoistedName)
	for _, name := range e.hoistedName {
		fmt.Fprintf(&b, "\n// %s is an inline object hoisted from the spec so its fields stay named.\n",
			name)
		b.WriteString(strings.TrimPrefix(e.hoisted[name], "\n"))
	}

	if len(e.openNames) > 0 {
		b.WriteString(emitOpenObjectRegistry(e.openNames))
	}

	return b.String(), nil
}

func (e *Emitter) emitDef(name string, def Node) (string, error) {
	if def.PrimaryType() != typeObject && !def.Has(kwProperties) {
		return "", fmt.Errorf("$defs/%s: not an object and not excluded — "+
			"add it to exclusions.go with a reason, or teach emit.go to handle it", name)
	}

	var b strings.Builder
	b.WriteString("\n")
	if d := def.Str("description"); d != "" {
		fmt.Fprintf(&b, "// %s %s\n", name, wrapComment(lowerFirst(d), "// "))
	}
	fmt.Fprintf(&b, "type %s struct {\n", name)

	required := def.Required()
	var jsonNames []string
	for i, prop := range def.PropertyNames() {
		qualified := name + "." + prop
		// Declared here rather than in the caller so hoisted inline objects are
		// accounted for on the same footing as top-level $defs.
		e.cov.DeclareProp(qualified)
		if reason := e.ex.Prop(qualified); reason != "" {
			fmt.Fprintf(&b, "\t// %s is NOT generated: %s\n", prop, wrapComment(reason, "\t// "))
			continue
		}
		node := def.Property(prop)
		typ, err := e.goTypeNamed(node, qualified, name+goName(prop))
		if err != nil {
			return "", err
		}
		if i > 0 {
			b.WriteString("\n")
		}
		writeField(&b, prop, typ, node, required[prop])
		jsonNames = append(jsonNames, prop)
		e.cov.EmitProp(qualified)
	}
	if def.isOpenObject() {
		emitExtraField(&b)
	}
	b.WriteString("}\n")
	if def.isOpenObject() {
		e.needsJSON = true
		e.openNames = append(e.openNames, name)
		b.WriteString(emitOpenObjectJSON(name, jsonNames))
	}
	return b.String(), nil
}

// goType maps a schema node to a Go type, refusing anything it cannot express.
func (e *Emitter) goType(n Node, where string) (string, error) {
	return e.goTypeNamed(n, where, "")
}

// goTypeNamed is goType with a name to use if an inline object must be hoisted.
// An empty hoistAs means hoisting is not available at this position, and an
// inline object is an error rather than a silent map[string]any.
func (e *Emitter) goTypeNamed(n Node, where, hoistAs string) (string, error) {
	if ref := n.Str("$ref"); ref != "" {
		return e.refType(ref, where)
	}
	switch t := n.PrimaryType(); t {
	case typeString:
		return typeString, nil
	case typeBool:
		return goBool, nil
	case typeInt:
		return ptrIf(goInt, n.Nullable()), nil
	case typeNum:
		return ptrIf(goFloat, n.Nullable()), nil
	case typeArray:
		return e.arrayType(n, where)
	case typeObject:
		return e.objectType(n, where, hoistAs)
	case "":
		if n.Has(kwOneOf) || n.Has(kwAnyOf) || n.Has(kwAllOf) {
			return "", fmt.Errorf("%s: union (oneOf/anyOf/allOf) with no named $def — "+
				"hoist it to a $def and exclude it, so the hand-written type stays authoritative", where)
		}
		return goAny, nil
	default:
		return "", fmt.Errorf("%s: unhandled JSON-Schema type %q", where, t)
	}
}

func ptrIf(t string, nullable bool) string {
	if nullable {
		return "*" + t
	}
	return t
}

func (e *Emitter) refType(ref, where string) (string, error) {
	target := strings.TrimPrefix(ref, "#/$defs/")
	if target == ref {
		return "", fmt.Errorf("%s: unsupported $ref %q — only #/$defs/<Name> is handled", where, ref)
	}
	if reason := e.ex.Def(target); reason != "" {
		// Referencing an excluded def: fall back to any, and say so in the
		// generated source rather than pretending the field is typed.
		return "any /* " + target + ": " + reason + " */", nil
	}
	return "*" + target, nil
}

func (e *Emitter) arrayType(n Node, where string) (string, error) {
	items, ok := n.Child("items")
	if !ok {
		return goAnySlice, nil
	}
	inner, err := e.goType(items, where+"[]")
	if err != nil {
		return "", err
	}
	// Slices of objects keep the pointer, for the same reason maps do: it is
	// what the hand-written types use ([]*Step, []*Predicate), it lets a caller
	// hold a reference rather than copying on each read, and a recursive shape
	// like Predicate.all_of cannot be a slice of values at all without boxing.
	return "[]" + inner, nil
}

// objectType handles the three object shapes the spec uses: a closed object with
// properties (hoisted to its own named type so its fields stay named), an open
// map with a typed value, and a bare open map.
func (e *Emitter) objectType(n Node, where, hoistAs string) (string, error) {
	if n.Has(kwProperties) {
		if hoistAs == "" {
			return "", fmt.Errorf("%s: inline object with properties in a position that cannot "+
				"be hoisted — lift it to a $def in the spec", where)
		}
		src, err := e.emitDef(hoistAs, n)
		if err != nil {
			return "", err
		}
		if _, done := e.hoisted[hoistAs]; !done {
			e.hoisted[hoistAs] = src
			e.hoistedName = append(e.hoistedName, hoistAs)
		}
		return "*" + hoistAs, nil
	}
	if ap, ok := n.Child("additionalProperties"); ok {
		inner, err := e.goType(ap, where+"{}")
		if err != nil {
			return "", err
		}
		// A map of objects keeps the pointer. It lets a caller distinguish an
		// explicit null from a value, matches what the hand-written types use
		// (Pack.Prompts, AgentsConfig.Members are both map[string]*T), and
		// avoids rewriting every `if def := m[k]; def != nil` in the repo for
		// no gain. Scalar values stay values.
		if strings.HasPrefix(inner, "*") {
			return "map[string]" + inner, nil
		}
		return "map[string]" + inner, nil
	}
	return goAnyMap, nil
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	// Leave acronyms and proper nouns alone.
	if len(s) > 1 && s[1] >= 'A' && s[1] <= 'Z' {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// wrapComment hard-wraps to keep generated lines under the repo's 120-column
// lint limit.
func wrapComment(s, prefix string) string {
	s = strings.Join(strings.Fields(s), " ")
	const width = 90
	if len(s) <= width {
		return s
	}
	var lines []string
	for len(s) > width {
		cut := strings.LastIndex(s[:width], " ")
		if cut <= 0 {
			cut = width
		}
		lines = append(lines, s[:cut])
		s = strings.TrimSpace(s[cut:])
	}
	if s != "" {
		lines = append(lines, s)
	}
	return strings.Join(lines, "\n"+prefix)
}

// writeField emits one struct field: its doc comment, Go type and tags.
//
// Shared by the object and union emitters so the omitempty and pointer rules
// cannot drift between them — they did briefly, and a rule applied in one place
// and not the other is the same silent gap in miniature.
func writeField(b *strings.Builder, prop, typ string, node Node, isRequired bool) {
	if d := node.Str("description"); d != "" {
		fmt.Fprintf(b, "\t// %s %s\n", goName(prop), wrapComment(lowerFirst(d), "\t// "))
	}
	tag := prop
	if !isRequired {
		tag = prop + ",omitempty"
		if needsPointer(node, typ) {
			typ = "*" + typ
		}
	}
	fmt.Fprintf(b, "\t%s %s `json:%q yaml:%q`\n", goName(prop), typ, tag, tag)
}

// needsPointer decides whether an optional property must be a pointer to keep
// "absent" distinct from "explicitly the zero value".
//
// Two cases require it:
//
//   - a non-zero default, where a plain field silently reverses the default.
//     `enabled: false` on a validator would serialize to nothing and reload as
//     enabled, turning a disabled guardrail back on.
//   - a numeric or boolean type, where the zero value is a legitimate setting.
//     `temperature: 0` and `max_tokens: 0` mean something; "unset" means
//     something else. The SDK relies on exactly this — conversation.go reads
//     Parameters.MaxTokens as a pointer and only applies it when non-nil.
//
// Strings and containers are deliberately NOT pointerized. Absent and empty are
// interchangeable for them in practice, and blanket pointers were the main
// reason an off-the-shelf generator was unusable here: it made 42% of fields
// pointers and would have changed every read site in the repo.
func needsPointer(n Node, typ string) bool {
	if !needsPointerForDefault(typ) {
		return false
	}
	if hasMeaningfulDefault(n) {
		return true
	}
	switch n.PrimaryType() {
	case typeInt, typeNum, typeBool:
		return true
	default:
		return false
	}
}

// hasMeaningfulDefault reports whether a property declares a default that is not
// the Go zero value for its type.
//
// Such a property needs THREE states, not two: absent (use the spec default),
// explicitly set to the zero value, and explicitly set to something else. A
// plain field with omitempty collapses the first two, which silently reverses
// the default — `enabled: false` on a validator would serialize to nothing and
// reload as enabled, turning a disabled guardrail back on. Dropping omitempty
// instead collapses it the other way, asserting `max_rounds: 0` where the author
// said nothing.
//
// A pointer is the only representation that keeps all three apart. The
// hand-written types reached the same conclusion independently — evals.EvalDef
// uses *bool for exactly this.
func hasMeaningfulDefault(n Node) bool {
	d, ok := n.Raw[kwDefault]
	if !ok {
		return false
	}
	switch v := d.(type) {
	case bool:
		return v
	case float64:
		return v != 0
	case string:
		return v != ""
	case nil:
		return false
	default: // arrays and objects
		return true
	}
}

// needsPointerForDefault reports whether a Go type should be made a pointer to
// preserve the absent/zero distinction. Slices, maps and any are already
// nilable, so they carry it without help.
func needsPointerForDefault(typ string) bool {
	for _, p := range []string{"*", "[]", "map[", goAny} {
		if strings.HasPrefix(typ, p) {
			return false
		}
	}
	return true
}
