apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: image-analysis-local
  description: Test image analysis using local image files
spec:
  task_type: media-analysis
  
  turns:
    - role: user
      parts:
        - type: text
          text: "What objects do you see in this image?"
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.jpg
            mime_type: image/jpeg
            detail: high
      assertions:
        - type: image_format
          params:
            formats:
              - png
            message: "Validate PNG format in assistant response."

    - role: user
      parts:
        - type: text
          text: "Compare these two images:"
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.jpg
            mime_type: image/jpeg
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.png
            mime_type: image/png
      assertions:
        - type: image_format
          params:
            formats:
              - jpeg
              - png
            message: "Validate JPEG and PNG formats in assistant response."

    - role: user
      parts:
        - type: text
          text: "Analyze this WebP image:"
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.webp
            mime_type: image/webp
            detail: auto
      assertions:
        - type: image_format
          params:
            formats:
              - webp
            message: "Validate WebP format in assistant response."
