apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: video-validation
  annotations:
    description: 'Demonstrates video duration and resolution validation using media
      assertions. Tests video_duration and video_resolution validators on assistant
      responses.

      '
spec:
  id: video-validation
  task_type: media-analysis
  turns:
  - role: user
    parts:
    - type: text
      text: Generate a short video clip
    assertions:
    - type: content_includes
      params:
        patterns:
        - video
    - type: video_duration
      params:
        min_seconds: 1
        max_seconds: 60
  - role: user
    parts:
    - type: text
      text: Create a 30-second video clip
    assertions:
    - type: video_duration
      params:
        min_seconds: 29
        max_seconds: 31
  - role: user
    parts:
    - type: text
      text: Generate a 720p HD video
    assertions:
    - type: video_resolution
      params:
        presets:
        - 720p
        - hd
  - role: user
    parts:
    - type: text
      text: Create a Full HD 1080p video
    assertions:
    - type: video_resolution
      params:
        presets:
        - 1080p
        - fhd
        - full_hd
  - role: user
    parts:
    - type: text
      text: Generate a 4K ultra HD video
    assertions:
    - type: video_resolution
      params:
        presets:
        - 4k
        - uhd
        - 2160p
  - role: user
    parts:
    - type: text
      text: Create a high-resolution video
    assertions:
    - type: video_resolution
      params:
        min_width: 1280
        min_height: 720
  - role: user
    parts:
    - type: text
      text: Generate a 1920x1080 video
    assertions:
    - type: video_resolution
      params:
        min_width: 1920
        max_width: 1920
        min_height: 1080
        max_height: 1080
  - role: user
    parts:
    - type: text
      text: Create a 1-minute 4K video clip
    assertions:
    - type: video_duration
      params:
        min_seconds: 59
        max_seconds: 61
    - type: video_resolution
      params:
        presets:
        - 4k
        - uhd
  - role: user
    parts:
    - type: text
      text: Generate a TikTok-style vertical video (9:16 aspect ratio)
    assertions:
    - type: video_duration
      params:
        max_seconds: 60
    - type: video_resolution
      params:
        min_width: 720
        min_height: 1280
  - role: user
    parts:
    - type: text
      text: 'Create videos in multiple resolutions: SD, HD, and 4K'
    assertions:
    - type: video_resolution
      params:
        presets:
        - 480p
        - 720p
        - 1080p
        - 4k
  - role: user
    parts:
    - type: text
      text: Generate a 5-minute tutorial video in 1080p
    assertions:
    - type: video_duration
      params:
        min_seconds: 290
        max_seconds: 310
    - type: video_resolution
      params:
        presets:
        - 1080p
  description: 'Demonstrates video duration and resolution validation using media
    assertions. Tests video_duration and video_resolution validators on assistant
    responses.

    '
