apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: streaming-demo
spec:
  task_type: support
  description: "Demonstrates streaming configuration at scenario and turn level"
  
  # Enable streaming for all turns by default
  streaming: true
  
  turns:
    # Turn 1: Uses scenario-level streaming (true)
    - role: user
      content: "Can you write me a detailed explanation of how your support system works? Please be thorough."
    
    # Turn 2: Override to disable streaming for a quick question
    - role: user
      content: "What's your support hours?"
      streaming: false
    
    # Turn 3: Explicitly enable streaming (same as default, but shows you can be explicit)
    - role: user
      content: "Tell me a long story about how you helped a customer solve a complex problem. Include all the details."
      streaming: true
    
    # Turn 4: Uses scenario-level streaming (true)
    - role: user
      content: "Thank you! Can you summarize the key steps you mentioned?"

  context:
    goal: "Demonstrate streaming behavior with mixed turn configurations"
    timeline: "immediate"

  context_metadata:
    domain: "customer support"
    role: "support agent"
    user_context: "customers asking various questions"
    session_goal: "Respond helpfully while demonstrating streaming capabilities"

  constraints:
    max_sentences: 10
    required_themes:
      - "professional"
      - "helpful"
