apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: streaming-demo
spec:
  task_type: support
  description: "Demonstrates streaming configuration at scenario and turn level"
  
  # Enable streaming for all turns by default
  streaming: true
  
  turns:
    # Turn 1: Uses scenario-level streaming (true)
    - role: user
      content: "Can you write me a detailed explanation of how your support system works? Please be thorough."
      assertions:
        - type: content_includes
          params:
            patterns: ["support system", "detailed", "thorough"]
            message: "Should provide comprehensive explanation of support system"
        - type: content_matches
          params:
            pattern: "(?i)(process|steps|team|help|assist|respond)"
            message: "Should describe support processes and capabilities"
    
    # Turn 2: Override to disable streaming for a quick question
    - role: user
      content: "What's your support hours?"
      streaming: false
      assertions:
        - type: content_includes
          params:
            patterns: ["hours", "available"]
            message: "Should provide support hours information"
        - type: content_matches
          params:
            pattern: "(?i)(24/7|24 hours|business hours|[0-9]+.*[ap]m|monday|available)"
            message: "Should specify actual support hours or availability"
    
    # Turn 3: Explicitly enable streaming (same as default, but shows you can be explicit)
    - role: user
      content: "Tell me a long story about how you helped a customer solve a complex problem. Include all the details."
      streaming: true
      assertions:
        - type: content_includes
          params:
            patterns: ["customer", "problem", "solution", "details"]
            message: "Should provide detailed customer success story"
        - type: content_matches
          params:
            pattern: "(?i)(once|customer|issue|problem|resolved|solved|steps|process)"
            message: "Should include narrative elements and problem-solving steps"
    
    # Turn 4: Uses scenario-level streaming (true)
    - role: user
      content: "Thank you! Can you summarize the key steps you mentioned?"
      assertions:
        - type: content_includes
          params:
            patterns: ["steps", "key", "summary"]
            message: "Should provide summarized key steps"
        - type: content_matches
          params:
            pattern: "(?i)(1|first|second|step|process|identify|understand|resolve)"
            message: "Should list or reference specific steps from previous response"

  context:
    goal: "Demonstrate streaming behavior with mixed turn configurations"
    timeline: "immediate"

  context_metadata:
    domain: "customer support"
    role: "support agent"
    user_context: "customers asking various questions"
    session_goal: "Respond helpfully while demonstrating streaming capabilities"

  constraints:
    max_sentences: 10
    required_themes:
      - "professional"
      - "helpful"
