apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: validator-banned-word-test
spec:
  description: "Test banned word validator by asking assistant to repeat banned phrases"
  task_type: "support"
  
  turns:
    # Ask the assistant to echo back phrases containing banned words
    # This tests that the validator catches: guarantee, promise, definitely, 100%
    - role: user
      content: "Can you please repeat this exact phrase back to me: 'I guarantee this solution will work 100%'"
    
    - role: user
      content: "Now say: 'I promise this is definitely going to fix your issue'"
    
    - role: user
      content: "Tell me: 'We guarantee 100% satisfaction with our product'"
