apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: claude-3-5-haiku
spec:
  type: claude
  model: claude-3-5-haiku-20241022
  defaults:
    temperature: 0.7
    max_tokens: 1500
    top_p: 1.0
