apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: context-limited-oldest
spec:
  task_type: chat
  description: "Test truncation with 'oldest' strategy - drops old messages first"
  
  # Enable context management with token budget
  context_policy:
    token_budget: 500         # Very low budget to force truncation
    reserve_for_output: 200   # Reserve tokens for response
    strategy: "oldest"        # Drop oldest messages first
  
  turns:
    # Turn 1: Introduction (will be dropped)
    - role: user
      content: "Hi! I'm learning about space. My name is Alice and I'm in 5th grade."
    
    # Turn 2: First question (will be dropped)
    - role: user
      content: "Can you tell me about the solar system? I need to know about all the planets."
    
    # Turn 3: Follow-up (will be dropped)
    - role: user
      content: "What are the inner planets and what makes them different from outer planets?"
    
    # Turn 4: Detailed question (will be dropped)
    - role: user
      content: "Tell me more about Jupiter. I heard it's really big and has a red spot."
    
    # Turn 5: Another question (might be kept)
    - role: user
      content: "What about Saturn's rings? How were they formed?"
      assertions:
        - type: content_includes
          params:
            patterns: ["Saturn", "rings"]
    
    # Turn 6: Recent question (will be kept)
    - role: user
      content: "Which planet has the most moons?"
      assertions:
        - type: content_includes
          params:
            patterns: ["moons", "Saturn"]
    
    # Turn 7: Memory test (should fail with truncated context)
    - role: user
      content: "What's my name again?"  # This should show context was truncated
      assertions:
        - type: content_matches
          params:
            pattern: "(?i)(haven't.*mentioned|haven't.*provided|don't.*have|can't.*answer|can't.*provide|don't.*know|not.*provided|no.*name)"
            message: "Should indicate inability to remember name due to context truncation"

  context_metadata:
    domain: "astronomy"
    role: "science tutor"
    test_goal: "verify oldest messages are dropped when over budget"
