apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: mixed-media
spec:
  task_type: media-analysis
  description: "Test mixing different media types (images and audio)"

  turns:
    - role: user
      parts:
        - type: text
          text: "Here's an image and an audio file together:"
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.jpg
            mime_type: image/jpeg
        - type: audio
          media:
            file_path: ../../tools/arena/testdata/media/test-audio-small.wav
            mime_type: audio/wav
      assertions:
        - type: image_format
          params:
            formats:
              - png
            message: "Validate PNG image format."
        - type: audio_format
          params:
            formats:
              - mp3
            message: "Validate MP3 audio format."

    - role: user
      parts:
        - type: text
          text: "Analyze these multiple images:"
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.jpg
            mime_type: image/jpeg
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.png
            mime_type: image/png
        - type: image
          media:
            file_path: ../../tools/arena/testdata/media/test-image-small.gif
            mime_type: image/gif
      assertions:
        - type: image_format
          params:
            formats:
              - jpeg
              - png
              - gif
            message: "Validate JPEG, PNG, and GIF image formats."
